
services:
  db:
    image: postgres:16.2
    restart: no
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=comic_db
      - POSTGRES_USER=comic_user
      - POSTGRES_PASSWORD=comic_pass
    ports:
      - "5432:5432"

  selenium:
    image: selenium/standalone-chrome:136.0
    restart: unless-stopped
    hostname: selenium
    ports:
      - "4444:4444"


  backend:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    command: [
      "/code/app/wait-for-it.sh", "db:5432", "--",
      "python", "/code/app/manage.py", "runserver", "0.0.0.0:8000", "--settings=config.settings.local"]
    restart: no
    volumes:
      - ./app/src:/code/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db


  # Uncomment when frontend is ready
  # ui:
  #   build:
  #     context: ./ui
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   restart: no

volumes:
  postgres_data:
