
services:
  db:
    image: postgres:16.2
    restart: no
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=comic_db
      - POSTGRES_USER=comic_user
      - POSTGRES_PASSWORD=comic_pass
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    command: ["/code/wait-for-it.sh", "db:5432", "--", "python", "/code/manage.py", "runserver", "0.0.0.0:8000"]
    restart: no
    volumes:
      - ./app/src:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  selenium:
    image: selenium/standalone-chrome:latest
    restart: no
    hostname: selenium
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm

  scrapy:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    working_dir: /code/comic_scrapers
    command: ["/code/wait-for-it.sh", "db:5432", "--", "tail", "-f", "/dev/null"]
    env_file:
      - ./.env
    depends_on:
      - db
      - selenium
    stdin_open: true
    tty: true
    volumes:
      - ./app/src:/code

  # Uncomment when frontend is ready
  # ui:
  #   build:
  #     context: ./ui
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - web
  #   restart: no

volumes:
  postgres_data:
