
services:
  db:
    image: postgres:16.2
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=comic_db
      - POSTGRES_USER=comic_user
      - POSTGRES_PASSWORD=comic_pass
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile.prod
    restart: unless-stopped
    command: [
      "/code/wait-for-it.sh", "db:5432", "--",
      "gunicorn", "--config", "config/gunicorn/gunicorn_config.py"]
    volumes:
      - ./app/src:/code
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - db

  selenium:
    image: selenium/standalone-chrome:latest
    restart: unless-stopped
    hostname: selenium
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm

  scrapy:
    build:
      context: .
      dockerfile: ./app/Dockerfile.prod
    working_dir: /code/comic_scrapers
    command: ["/code/wait-for-it.sh", "db:5432", "--", "tail", "-f", "/dev/null"]
    env_file:
      - ./.env
    depends_on:
      - db
      - selenium
    stdin_open: true
    tty: true
    volumes:
      - ./app/src:/code

  # Uncomment when frontend is ready
  # ui:
  #   build:
  #     context: ./ui
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - web
  #   restart: no

  nginx:
    image: nginx:1.25.5
    restart: unless-stopped
    ports:
      - "80:80"  # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ./app/src/config/nginx:/etc/nginx/templates
      - ./app/src/ssl:/code/ssl:ro
      - ./app/src/static:/code/static:ro
    depends_on:
      - web
volumes:
  postgres_data:
